function json(data, status = 200) {
  return new Response(JSON.stringify(data), { status, headers: { 'content-type': 'application/json; charset=utf-8', 'cache-control': 'no-store' } });
}
function parseSplitWith(value) { try { const parsed = JSON.parse(value || '[]'); return Array.isArray(parsed) ? parsed : []; } catch { return []; } }
const DEFAULT_ROUTE_DAYS=[{id:'day-1',dayIndex:0,prefix:'Day 1',city:'Tokyo'},{id:'day-2',dayIndex:1,prefix:'Day 2',city:'Tokyo'},{id:'day-3',dayIndex:2,prefix:'Day 3',city:'Tokyo'},{id:'day-4',dayIndex:3,prefix:'Day 4',city:'Kamakura / Yokohama'},{id:'day-5',dayIndex:4,prefix:'Day 5',city:'Hakone'},{id:'day-6',dayIndex:5,prefix:'Day 6',city:'Yokohama'},{id:'departure',dayIndex:6,prefix:'Departure',city:'Yokohama / Narita'}];
async function ensureSchema(env){
  await env.DB.prepare(`CREATE TABLE IF NOT EXISTS expenses (id TEXT PRIMARY KEY, day TEXT NOT NULL, payer TEXT NOT NULL, amount_jpy REAL NOT NULL, original_amount REAL NOT NULL, original_currency TEXT NOT NULL, category TEXT NOT NULL, note TEXT, split_with TEXT NOT NULL, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`).run();
  await env.DB.prepare(`CREATE TABLE IF NOT EXISTS plans (id TEXT PRIMARY KEY, day TEXT NOT NULL, time TEXT, title TEXT NOT NULL, location TEXT, notes TEXT, completed INTEGER NOT NULL DEFAULT 0, order_index INTEGER NOT NULL DEFAULT 0, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`).run();
  await env.DB.prepare(`CREATE TABLE IF NOT EXISTS route_days (id TEXT PRIMARY KEY, day_index INTEGER NOT NULL, prefix TEXT NOT NULL, city TEXT NOT NULL, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`).run();
  const columns=await env.DB.prepare(`PRAGMA table_info(plans)`).all(); const names=new Set((columns.results||[]).map(c=>c.name));
  if(!names.has('completed')) await env.DB.prepare(`ALTER TABLE plans ADD COLUMN completed INTEGER NOT NULL DEFAULT 0`).run();
  if(!names.has('order_index')) await env.DB.prepare(`ALTER TABLE plans ADD COLUMN order_index INTEGER NOT NULL DEFAULT 0`).run();
  const countRow=await env.DB.prepare(`SELECT COUNT(*) AS count FROM route_days`).first();
  if(!countRow||Number(countRow.count||0)===0){await env.DB.batch(DEFAULT_ROUTE_DAYS.map(d=>env.DB.prepare(`INSERT INTO route_days (id, day_index, prefix, city) VALUES (?, ?, ?, ?)`).bind(d.id,d.dayIndex,d.prefix,d.city)));}
}
async function getExpenses(env){await ensureSchema(env);const result=await env.DB.prepare(`SELECT id, day, payer, amount_jpy AS amountJPY, original_amount AS originalAmount, original_currency AS originalCurrency, category, note, split_with AS splitWith, created_at AS createdAt FROM expenses ORDER BY created_at DESC`).all();return json({expenses:result.results.map(row=>({...row,splitWith:parseSplitWith(row.splitWith)}))});}
async function addExpense(request,env){await ensureSchema(env);const body=await request.json();const id=body.id||crypto.randomUUID();await env.DB.prepare(`INSERT OR REPLACE INTO expenses (id, day, payer, amount_jpy, original_amount, original_currency, category, note, split_with) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)`).bind(id,body.day||'',body.payer||'',Number(body.amountJPY||0),Number(body.originalAmount||0),body.originalCurrency||'JPY',body.category||'Other',body.note||'',JSON.stringify(body.splitWith||[])).run();return json({ok:true,id},201);}
async function deleteExpense(request,env){const id=new URL(request.url).searchParams.get('id');if(!id)return json({error:'Missing id'},400);await env.DB.prepare('DELETE FROM expenses WHERE id = ?').bind(id).run();return json({ok:true});}
async function getPlans(env){await ensureSchema(env);const result=await env.DB.prepare(`SELECT id, day, time, title, location, notes, completed, order_index AS orderIndex, created_at AS createdAt FROM plans ORDER BY day ASC, order_index ASC, time ASC, created_at ASC`).all();return json({plans:result.results});}
async function addPlan(request,env){await ensureSchema(env);const body=await request.json();const id=body.id||crypto.randomUUID();await env.DB.prepare(`INSERT OR REPLACE INTO plans (id, day, time, title, location, notes, completed, order_index) VALUES (?, ?, ?, ?, ?, ?, ?, ?)`).bind(id,body.day||'',body.time||'',body.title||'',body.location||'',body.notes||'',Number(body.completed||0),Number(body.orderIndex||0)).run();return json({ok:true,id},201);}
async function updatePlan(request,env){await ensureSchema(env);const body=await request.json();if(!body.id)return json({error:'Missing id'},400);const existing=await env.DB.prepare('SELECT * FROM plans WHERE id = ?').bind(body.id).first();if(!existing)return json({error:'Plan not found'},404);await env.DB.prepare(`UPDATE plans SET day = ?, time = ?, title = ?, location = ?, notes = ?, completed = ?, order_index = ? WHERE id = ?`).bind(body.day??existing.day,body.time??existing.time,body.title??existing.title,body.location??existing.location,body.notes??existing.notes,Number(body.completed??existing.completed??0),Number(body.orderIndex??existing.order_index??0),body.id).run();return json({ok:true,id:body.id});}
async function reorderPlans(request,env){await ensureSchema(env);const body=await request.json();const plans=Array.isArray(body.plans)?body.plans:[];const statements=plans.filter(p=>p.id).map(p=>env.DB.prepare('UPDATE plans SET day = ?, order_index = ? WHERE id = ?').bind(p.day||'',Number(p.orderIndex||0),p.id));if(statements.length)await env.DB.batch(statements);return json({ok:true,count:statements.length});}
async function deletePlan(request,env){const id=new URL(request.url).searchParams.get('id');if(!id)return json({error:'Missing id'},400);await env.DB.prepare('DELETE FROM plans WHERE id = ?').bind(id).run();return json({ok:true});}
async function getRouteDays(env){await ensureSchema(env);const result=await env.DB.prepare(`SELECT id, day_index AS dayIndex, prefix, city, updated_at AS updatedAt FROM route_days ORDER BY day_index ASC`).all();return json({routeDays:result.results});}
async function saveRouteDays(request,env){await ensureSchema(env);const body=await request.json();const routeDays=Array.isArray(body.routeDays)?body.routeDays:[];if(!routeDays.length)return json({error:'Missing routeDays'},400);const statements=routeDays.map((day,index)=>env.DB.prepare(`INSERT OR REPLACE INTO route_days (id, day_index, prefix, city, updated_at) VALUES (?, ?, ?, ?, CURRENT_TIMESTAMP)`).bind(day.id||`day-${index+1}`,Number(day.dayIndex??index),day.prefix||`Day ${index+1}`,day.city||'Flexible'));await env.DB.batch(statements);return json({ok:true,count:statements.length});}
export default { async fetch(request, env) { const url=new URL(request.url); if(url.pathname==='/api/health'){await ensureSchema(env);const row=await env.DB.prepare("SELECT datetime('now') AS now").first();return json({ok:true,database:'connected',now:row.now});} if(url.pathname==='/api/expenses'){if(request.method==='GET')return getExpenses(env);if(request.method==='POST')return addExpense(request,env);if(request.method==='DELETE')return deleteExpense(request,env);return json({error:'Method not allowed'},405);} if(url.pathname==='/api/plans'){if(request.method==='GET')return getPlans(env);if(request.method==='POST')return addPlan(request,env);if(request.method==='PATCH')return updatePlan(request,env);if(request.method==='DELETE')return deletePlan(request,env);return json({error:'Method not allowed'},405);} if(url.pathname==='/api/plans/reorder'){if(request.method==='POST')return reorderPlans(request,env);return json({error:'Method not allowed'},405);} if(url.pathname==='/api/route-days'){if(request.method==='GET')return getRouteDays(env);if(request.method==='PUT')return saveRouteDays(request,env);return json({error:'Method not allowed'},405);} return env.ASSETS.fetch(request); } };
