name = "toyk"
main = "worker.js"
compatibility_date = "2026-05-21"

[assets]
directory = "./public"
binding = "ASSETS"

# Replace database_id after creating/binding your Cloudflare D1 database.
[[d1_databases]]
binding = "DB"
database_name = "japan-trip-2026-db"
database_id = "82124be9-c0a2-448c-a183-b2b1b94f2085"
